# CI Workflow: Checkstyle Analysis
#
# Description:
#   This workflow performs static code analysis to identify potential issues such as coding standards violations,
#   code smells, and potential bugs using Checkstyle. It helps mastertain code quality and readability.
#
# Triggers:
#   - Pushes to the master branch
#   - Pull requests targeting the master branch
#
# Steps:
#   1. Checkout code: Fetches the codebase associated with the specified branch or pull request from the VCS repository.
#   2. Set up JDK: Sets up the Java environment using the specified JDK version.
#   3. Static Code Analysis: Executes Checkstyle, a static code analysis tools such as Checkstyle, using Maven commands.
#
name: Checkstyle Analysis

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          check-latest: true

      - name: Static Code Analysis
        run: mvn checkstyle:checkstyle

      - if: steps.cache.outputs.cache-hit != 'true'
        name: Install Maven dependencies
        run: mvn dependency:go-offline
