# CD Workflow: Deploy to AWS Elastic Beanstalk
#
# Description:
#   This workflow automates the deployment of a Dockerized application to AWS Elastic Beanstalk. It builds the Docker image,
#   generates a deployment package, and deploys the application to an Elastic Beanstalk environment.
#
# Triggers:
#   - Pushes to the master branch
#
# Steps:
#   1. Checkout Latest Repo: Fetches the latest codebase associated with the master branch from the version control system.
#   2. Set up Docker Buildx: Sets up Docker Buildx for building multi-platform Docker images.
#   3. Login to DockerHub: Logs in to DockerHub registry using the provided credentials.
#   4. Build and push: Builds the Docker image specified in the Dockerfile and pushes it to DockerHub.
#   5. Get Timestamp: Retrieves the current timestamp to use as a version label for the deployment.
#   6. Run String Replace: Replaces characters in the timestamp to ensure a valid version label format.
#   7. Generate Deployment Package: Creates a deployment package by compressing the application files.
#   8. Deploy to EB: Deploys the application to AWS Elastic Beanstalk using the generated deployment package, AWS credentials,
#      application name, environment name, and version label. It triggers the deployment process in the specified AWS region.
#
name: Prod deployment from Github to AWS Elastic Beanstalk
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: kevindocker123/unit-conversion:latest

      - name: Get Timestamp
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Run String Replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: "-"
          flags: "g"

      - name: Generate Deployment Package
        run: zip -r deploy.zip * -x "**target**"

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: UnitConversion
          environment_name: UnitConversion-env
          version_label: "docker-app-${{ steps.format-time.outputs.replaced }}"
          region: us-east-1
          deployment_package: deploy.zip
