# CI Workflow: Static Code Analysis
#
# Description:
#   This workflow performs static code analysis to identify potential issues such as coding standards violations,
#   code smells, and potential bugs. It helps mastertain code quality and readability.
#
# Triggers:
#   - Pushes to the master branch
#   - Pull requests targeting the master branch
#
# Steps:
#   1. Checkout code: Fetches the codebase associated with the specified branch or pull request from the VCS repository.
#   2. Set up JDK: Sets up the Java environment using the specified JDK version.
#   3. Static Code Analysis: Executes static code analysis tools such as Checkstyle and PMD using Maven commands.
#
name: Static Code Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        check-latest: true

    - name: Static Code Analysis
      run: |
        # Example: Run Checkstyle
        mvn checkstyle:checkstyle
        # Example: Run PMD
        # mvn pmd:pmd
