# CI Workflow: Run Unit Tests
#
# Description:
#   This workflow executes unit tests to validate the correctness of individual components or units of code.
#   It ensures that the code behaves as expected at a granular level.
#
# Triggers:
#   - Pushes to the master branch
#   - Pull requests targeting the master branch
#
# Steps:
#   1. Checkout code: Fetches the codebase associated with the specified branch or pull request from the VCS repository.
#   2. Set up JDK: Sets up the Java environment using the specified JDK version.
#   3. Run Unit Tests: Executes unit tests by running Maven commands.
#
name: Run Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        check-latest: true

    - name: Run Unit Tests
      run: mvn test --file pom.xml
